### ISSUE TITLE
ValueError: got_ver is None on installing transformers

### ISSUE THREAD

**Issue by sankalp-wns** [aws-samples/amazon-sagemaker-bert-pytorch#11]
I am using the same approach for another transformers model - LayoutLMv2. However, the training job fails with the below error. It seems that transformers dependencies are not loaded properly.

```
UnexpectedStatusException: Error for Training job pytorch-training-2022-05-29-18-38-24-543: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/opt/conda/bin/python train_deploy.py --epochs 6 --num_labels 7"
Traceback (most recent call last):
  File "train_deploy.py", line 12, in <module>
    from transformers import AdamW, LayoutLMv2Processor, LayoutLMv2ForTokenClassification
  File "/opt/conda/lib/python3.6/site-packages/transformers/__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "/opt/conda/lib/python3.6/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/opt/conda/lib/python3.6/site-packages/transformers/utils/versions.py", line 120, in require_version_core
    return require_version(requirement, hint)
  File "/opt/conda/lib/python3.6/site-packages/transformers/utils/versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/opt/conda/lib/python3.6/site-packages/transformers/utils/versions.py", line 45, in _compare_versions
```

I tried running the script directly by creating a venv environment with the requirements file provided for training and it works fine. 
How do I debug this issue?

**Comment by sankalp-wns** [comment]
My PyTorch framework version was wrong in the estimator. Fixed it and now working.
