### ISSUE TITLE
When use larger instance, get error

### ISSUE THREAD

**Issue by snowolf** [aws-samples/amazon-sagemaker-bert-pytorch#3]
Hi, 
I want to use multi-gpu in one instance, for example, p3.8xlarge has 4 gpu. However when I change train_instance_type="ml.p3.2xlarge" to 'ml.p3.8xlarge', would get error like below:

[2020-09-02 15:22:37.902 algo-1:76 INFO utils.py:25] The end of training job file will not be written for jobs running under SageMaker.
2020-09-02 15:22:38,696 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/opt/conda/bin/python train_deploy.py --backend gloo --epochs 1 --num_labels 2"
Traceback (most recent call last):
  File "train_deploy.py", line 327, in <module>
    train(parser.parse_args())
  File "train_deploy.py", line 187, in train
    outputs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 444, in forward
    outputs = self.parallel_apply(self._module_copies[:len(inputs)], inputs, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 469, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/transformers/modeling_bert.py", line 1032, in forward
    inputs_embeds=inputs_embeds)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/transformers/modeling_bert.py", line 735, in forward
    embedding_output = self.embeddings(input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/transformers/modeling_bert.py", line 186, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 554, in __call__
    hook_result = hook(self, input, result)
  File "/opt/conda/lib/python3.6/site-packages/smdebug/pytorch/hook.py", line 153, in forward_hook
    module_name = self.module_maps[module]
KeyError: Embedding(30522, 768, padding_idx=0)

**Comment by billdoors** [comment]
https://discuss.pytorch.org/t/error-in-torch-nn-dataparallel/64164/9  this might be the issue.

**Comment by snowolf** [comment]
> https://discuss.pytorch.org/t/error-in-torch-nn-dataparallel/64164/9 this might be the issue.

Hi, I try use 2 x ml.p3.8xlarge, each instance has 4 GPU and in total 8 GPU, and the batch size is 64, test-batch-size is 512, which could be divided by 8 and 4, however the issue still exist.

**Comment by snowolf** [comment]
```
if is_distributed:
        # Initialize the distributed environment.
        world_size = len(args.hosts)
        os.environ["WORLD_SIZE"] = str(world_size)
        host_rank = args.hosts.index(args.current_host)
        os.environ["RANK"] = str(host_rank)
        dist.init_process_group(backend=args.backend, rank=host_rank, world_size=world_size)
        logger.info(
            "Initialized the distributed environment: '%s' backend on %d nodes. "
            "Current host rank is %d. Number of gpus: %d",
            args.backend, dist.get_world_size(),
            dist.get_rank(), args.num_gpus
        )
```

The world_size is determined by how many hosts, so this code only use single card on each host, could not used in multi-cards instance.

**Comment by billdoors** [comment]
Thanks for your notes. Please feel free to create a pull request to enable multi-card instance. Thanks.
